### ISSUE TITLE
No module named 'bit_config'

### ISSUE THREAD

**Issue by leiwen83** [Zhen-Dong/HAWQ#1]
Hi,

I try to run quant_train.py, but meet the error as below, how to solve it ?

Traceback (most recent call last):
  File "quant_train.py", line 22, in <module>
    from bit_config import *
ModuleNotFoundError: No module named 'bit_config'

Thx,
Lei

**Comment by Zhen-Dong** [comment]
Hi Lei, thanks for pointing this out. I think this issue was solved by some recent commits, so please pull the current repo.
Specifically, we moved the bit_config.py into the tvm_benchmark folder and imported the module from there.
Feel free to reach out if this doesn't work.

**Comment by Zhen-Dong** [comment]
To follow up, I submit a new commit moving bit_config.py out of the tvm_benchmark folder, I think this could make the codes more straightforward.

**Comment by leiwen83** [comment]
great! it works!
