### ISSUE TITLE
Issue on dict_keys

### ISSUE THREAD

**Issue by wowow11111** [Zhen-Dong/HAWQ#10]
I found an issue trying to run your model on TVM.

When I tried to run 
python hawq_utils_resnet50.py --model-dir ./data/resnet18_uniform4/  (assuming I want to run resnet18, uniform4 based trained model)
This error appears
----------------------------------------------
Traceback (most recent call last):

  File "/home/kjk2020/tvm-newHAWQ/tvm_benchmark/hawq_utils_resnet50.py", line 483, in <module>
    weight_integer = model['weight_integer']

KeyError: 'weight_integer'
--------------------------------------------------

and when I print out the keys of model, this appears
dict_keys(['epoch', 'arch', 'state_dict', 'best_acc1', 'optimizer'])

which do not include weight_integer ,,,

Also, I just wanted to run the '6. Measure inference time (with uniform int4/int8 or custom mixed-precision bit configs in bit_config.py).' part but I get errors 
because some part of information ("all_impls" variable in "/--/tvm/python/tvm/relay/backend/compile_engine.py : 150") 
is empty, and as I follow those error traces(the former empty parts), that leads to external api functions. 
Here's the error code
---------------------------------------------------
Traceback (most recent call last):

  File "/home/kjk2020/tvm-newHAWQ/tvm_benchmark/test_resnet_inference_time.py", line 235, in <module>
    graph, lib, params = relay.build(func, target=TARGET_NAME, params=params)

  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/relay/build_module.py", line 251, in build
    graph_json, mod, params = bld_mod.build(mod, target, target_host, params)

  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/relay/build_module.py", line 120, in build
    self._build(mod, target, target_host)

  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 219, in __call__
    raise get_last_ffi_error()

KeyError: 'Traceback (most recent call last):\n  [bt] (8) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::relay::ExprMutator::VisitExpr(tvm::RelayExpr const&)+0x8e) [0x7f63bba4269e]\n  [bt] (7) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>::VisitExpr(tvm::RelayExpr const&)+0x91) [0x7f63bba47651]\n  [bt] (6) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>::InitVTable()::{lambda(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>*)#6}::_FUN(tvm::runtime::ObjectRef const&, tvm::relay::ExprFunctor<tvm::RelayExpr (tvm::RelayExpr const&)>*)+0x27) [0x7f63bba44627]\n  [bt] (5) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::relay::MixedModeMutator::VisitExpr_(tvm::relay::CallNode const*)+0x43) [0x7f63bb8e9d73]\n  [bt] (4) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::relay::ForwardRewriter::Rewrite_(tvm::relay::CallNode const*, tvm::RelayExpr const&)+0x745) [0x7f63bb8ed215]\n  [bt] (3) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(void tvm::runtime::detail::unpack_call<tvm::RelayExpr, 3, tvm::RelayExpr (*)(tvm::relay::Call const&, tvm::Array<tvm::RelayExpr, void> const&, tvm::runtime::ObjectRef const&)>(tvm::RelayExpr (* const&)(tvm::relay::Call const&, tvm::Array<tvm::RelayExpr, void> const&, tvm::runtime::ObjectRef const&), tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)+0x210) [0x7f63bb875bf0]\n  [bt] (2) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::RelayExpr tvm::relay::LayoutRewriter<tvm::relay::alter_op_layout::AlterTransformMemorizer>(tvm::relay::Call const&, tvm::Array<tvm::RelayExpr, void> const&, tvm::runtime::ObjectRef const&)+0xa45) [0x7f63bb8736f5]\n  [bt] (1) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(tvm::relay::alter_op_layout::AlterTransformMemorizer::CallWithNewLayouts(tvm::relay::Call const&, std::vector<tvm::RelayExpr, std::allocator<tvm::RelayExpr> > const&)+0x773) [0x7f63bb8711f3]\n  [bt] (0) /home/kjk2020/tvm-newHAWQ/tvm/build/libtvm.so(+0x13434fb) [0x7f63bbb174fb]\n  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 78, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/relay/op/nn/_nn.py", line 98, in alter_op_layout_conv2d\n    return topi.nn.conv2d_alter_layout(attrs, inputs, tinfos, out_type)\n  File "<decorator-gen-39>", line 2, in conv2d_alter_layout\n  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/target/generic_func.py", line 267, in dispatch_func\n    return dispatch_dict[k](*args, **kwargs)\n  File "/home/kjk2020/tvm-newHAWQ/tvm/topi/python/topi/cuda/conv2d_alter_op.py", line 39, in _alter_conv2d_layout\n    relay.op.get("nn.conv2d"), attrs, tinfos, out_type, target)\n  File "/home/kjk2020/tvm-newHAWQ/tvm/python/tvm/relay/backend/compile_engine.py", line 229, in select_implementation\n    return best_plevel_impl, outputs[best_plevel_impl]\nKeyError: None'

**Comment by wowow11111** [comment]
I can pull out only the dictionaries names with xxx.yyy.weight_integer but doesn't seem right cuz what follows is save_weight.

**Comment by zachzzc** [comment]
The hawq_utils_resnet50 is now hard-coded to be used for resnet50 but can be easily modified to resnet18. You can start with resnet50 first.

**Comment by wowow11111** [comment]
Thanks for the reply, I modified to resnet 18, and successfully ran it. Can you also upload the resnet50 uniform8 file with the same format "quantized_checkpoint.tar.pth" file? The one that was uploaded before did not contain the file, and now the whole file is gone I think.

**Comment by KunmingS** [comment]
Change the '==' to '>=' in https://github.com/zachzzc/incubator-tvm/blob/master/python/tvm/contrib/nvcc.py#L264 may help.

**Comment by fuhaifei** [comment]
> Change the '==' to '>=' in https://github.com/zachzzc/incubator-tvm/blob/master/python/tvm/contrib/nvcc.py#L264 may help.

> Also, I just wanted to run the '6. Measure inference time (with uniform int4/int8 or custom mixed-precision bit configs in bit_config.py).' part but I get errors
because some part of information ("all_impls" variable in "/--/tvm/python/tvm/relay/backend/compile_engine.py : 150")
is empty, and as I follow those error traces(the former empty parts), that leads to external api functions.
Here's the error code

Are you suggesting that if I follow your method and rebuild TVM, the second issue mentioned by [wowow11111](https://github.com/wowow11111) will no longer occur?
