### ISSUE TITLE
LpProblem和Hutchinson_trace方便开源一下？

### ISSUE THREAD

**Issue by 666DZY666** [Zhen-Dong/HAWQ#36]

**Comment by qiulinzhang** [comment]
请问LpProblem和Hutchinson_trace是开源的吗？文件夹里面没有找到，也没有找到混合比特如何进行分配的代码

**Comment by H-cool** [comment]
> 请问LpProblem和Hutchinson_trace是开源的吗？文件夹里面没有找到，也没有找到混合位如何进行分配的代码

你好，请问你们有复现成功这个问题吗
